export enum PostActions {
  FETCH_POSTS = "FETCH_POSTS",
  CREATE_POST = "CREATE_POST",
  UPDATE_POST = "UPDATE_POST",
  DELETE_POST = "DELETE_POST",
  LIKE_POST = "LIKE_POST",
  GET_POST_BY_SEARCH = "GET_POST_BY_SEARCH",
}
